apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    run: demo-app
spec:
  type: NodePort
  ports:
  - port: 8200
    targetPort: 8080
  selector:
    app: demo-app
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: demo-app
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: Rolling
    rollingParams:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demoapp-pod
        image: naru014/kubernetessampleapp:21
        ports:
        - containerPort: 80
